spring:
  application:
    name: app-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:utilitybox}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:khanh123}

server:
  port: 8082
  servlet:
    context-path: /

openapi:
  service:
    title: app-service doc
    version: 1.0.0
    url: http://${OPEN_API_HOST:localhost}:${OPEN_API_PORT:8080}
springdoc:
  api-docs:
    path: /app-service/v3/api-docs
  swagger-ui:
    path: /app-service/swagger-ui.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      fetchRegistry: false
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
