version: "3.7"

services:
  eureka-server:
    image: hdkhanh222/utilitybox_eureka-server:0.0.1
    build:
      context: backend/eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"

  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=khanh123
      - POSTGRES_DB=utilitybox
    volumes:
      - ./backend/data-load/database-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api-gateway:
    image: hdkhanh222/utilitybox_api-gateway:0.0.1
    build:
      context: backend/api-gateway
      dockerfile: ./Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - application.uis.home=http://home:3000
      - application.services.auth=lb://AUTH-SERVICE
      - application.services.app=lb://APP-SERVICE
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    links:
      - eureka-server

  auth-service:
    image: hdkhanh222/utilitybox_auth-service:0.0.1
    build:
      context: backend/auth-service
      dockerfile: ./Dockerfile
    ports:
      - "8081"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres-db:5432/utilitybox
      - spring.datasource.username=admin
      - spring.datasource.password=khanh123
      - openapi.service.url=http://localhost:8080
      - eureka.client.fetch-with-eureka=false
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    restart: on-failure
    depends_on:
      - postgres-db
      - eureka-server
    links:
      - eureka-server

  app-service:
    image: hdkhanh222/utilitybox_app-service:0.0.1
    build:
      context: backend/app-service
      dockerfile: ./Dockerfile
    ports:
      - "8082"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres-db:5432/utilitybox
      - spring.datasource.username=admin
      - spring.datasource.password=khanh123
      - openapi.service.url=http://localhost:8080
      - eureka.client.fetch-with-eureka=false
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    restart: on-failure
    depends_on:
      - postgres-db
      - eureka-server
    links:
      - eureka-server

#  Recommend using the S3 package
#  json-formatter:
#    image: hdkhanh222/utilitybox_json-formatter:0.0.1
#    build:
#      context: frontend/json-formatter
#      dockerfile: ./Dockerfile
#    ports:
#      - "3002:3002"

  home:
    image: hdkhanh222/utilitybox_home:0.0.1
    build:
      context: frontend/home
      dockerfile: ./Dockerfile
    ports:
      - "3000"
