apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.utilitybox.authService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.utilitybox.authService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.utilitybox.authService.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.utilitybox.authService.name }}
          image: "{{ .Values.image.username }}/{{ .Values.utilitybox.authService.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http-auth
              containerPort: {{ .Values.utilitybox.authService.port }}
          env:
            - name: EUREKA_HOST
              value: {{ .Values.utilitybox.eurekaServer.name }}.default
            - name: EUREKA_PORT
              value: "{{ .Values.utilitybox.eurekaServer.port }}"
            - name: POSTGRES_HOST
              value: {{ .Values.utilitybox.postgres.name }}.default
            - name: POSTGRES_PORT
              value: "{{ .Values.utilitybox.postgres.port }}"
            - name: POSTGRES_USER
              value: {{ .Values.utilitybox.postgres.username }}
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.utilitybox.postgres.password }}"
            - name: POSTGRES_DB
              value: {{ .Values.utilitybox.postgres.database }}
            - name: OPEN_API_HOST
              value: {{ .Values.utilitybox.apiGateway.name }}.default
            - name: OPEN_API_PORT
              value: "{{ .Values.utilitybox.apiGateway.port }}"
