apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.utilitybox.authService.name }}
spec:
  ports:
    - name: http-auth
      port: {{ .Values.utilitybox.authService.port }}
      targetPort: {{ .Values.utilitybox.authService.port }}
      protocol: TCP
  selector:
    app: {{ .Values.utilitybox.authService.name }}
