apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.utilitybox.appService.name }}
spec:
  ports:
    - name: http-app
      port: {{ .Values.utilitybox.appService.port }}
      targetPort: {{ .Values.utilitybox.appService.port }}
      protocol: TCP
  selector:
    app: {{ .Values.utilitybox.appService.name }}
