apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.utilitybox.apiGateway.name }}
spec:
{{- with .Values.utilitybox.apiGateway.nodePort }}
  # node port for local test purpose
  type: NodePort
{{- end }}
  ports:
    - name: http-gateway
      port: {{ .Values.utilitybox.apiGateway.port }}
      targetPort: {{ .Values.utilitybox.apiGateway.port }}
      nodePort: {{ .Values.utilitybox.apiGateway.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.utilitybox.apiGateway.name }}
